package com.popcap.flash.games.blitz3game.resources
{
   public class Blitz3GameLoc
   {
      
      public static const LOC_BOOSTS_AUTORENEW_PRICES_CHANGED:String = "LOC_BLITZ3GAME_BOOSTS_AUTORENEW_PRICES_CHANGED";
      
      public static const LOC_BOOSTS_AUTORENEW_PRICES_CHANGED_CONTINUE:String = "LOC_BLITZ3GAME_BOOSTS_AUTORENEW_PRICES_CHANGED_CONTINUE";
      
      public static const LOC_BOOSTS_AUTORENEW_PRICES_CHANGED_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_AUTORENEW_PRICES_CHANGED_TITLE";
      
      public static const LOC_BOOSTS_DETONATOR_DESCRIPTION:String = "LOC_BLITZ3GAME_BOOSTS_DETONATOR_DESCRIPTION";
      
      public static const LOC_BOOSTS_DETONATOR_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_DETONATOR_TITLE";
      
      public static const LOC_BOOSTS_GEM_DESCRIPTION:String = "LOC_BLITZ3GAME_BOOSTS_GEM_DESCRIPTION";
      
      public static const LOC_BOOSTS_GEM_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_GEM_TITLE";
      
      public static const LOC_BOOSTS_MULTIPLIER_DESCRIPTION:String = "LOC_BLITZ3GAME_BOOSTS_MULTIPLIER_DESCRIPTION";
      
      public static const LOC_BOOSTS_MULTIPLIER_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_MULTIPLIER_TITLE";
      
      public static const LOC_BOOSTS_SCRAMBLER_DESCRIPTION:String = "LOC_BLITZ3GAME_BOOSTS_SCRAMBLER_DESCRIPTION";
      
      public static const LOC_BOOSTS_SCRAMBLER_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_SCRAMBLER_TITLE";
      
      public static const LOC_BOOSTS_TIME_DESCRIPTION:String = "LOC_BLITZ3GAME_BOOSTS_TIME_DESCRIPTION";
      
      public static const LOC_BOOSTS_TIME_TITLE:String = "LOC_BLITZ3GAME_BOOSTS_TIME_TITLE";
      
      public static const LOC_BOOSTS_TIPS_BUY:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_BUY";
      
      public static const LOC_BOOSTS_TIPS_FREE:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_FREE";
      
      public static const LOC_BOOSTS_TIPS_IN_USE:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_IN_USE";
      
      public static const LOC_BOOSTS_TIPS_LEFT:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_LEFT";
      
      public static const LOC_BOOSTS_TIPS_LIMIT:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_LIMIT";
      
      public static const LOC_BOOSTS_TIPS_MORE_COINS:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_MORE_COINS";
      
      public static const LOC_BOOSTS_TIPS_MORE_NEEDED:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_MORE_NEEDED";
      
      public static const LOC_BOOSTS_TIPS_SELL:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_SELL";
      
      public static const LOC_BOOSTS_TIPS_SOLD:String = "LOC_BLITZ3GAME_BOOSTS_TIPS_SOLD";
      
      public static const LOC_BOOST_ABANDON_CONFIRM:String = "LOC_BLITZ3GAME_BOOST_ABANDON_CONFIRM";
      
      public static const LOC_BOOST_ABANDON_DECLINE:String = "LOC_BLITZ3GAME_BOOST_ABANDON_DECLINE";
      
      public static const LOC_BOOST_ABANDON_DETAILS:String = "LOC_BLITZ3GAME_BOOST_ABANDON_DETAILS";
      
      public static const LOC_BOOST_MENU_CONTINUE:String = "LOC_BLITZ3GAME_BOOST_MENU_CONTINUE";
      
      public static const LOC_BOOST_MENU_HEADER:String = "LOC_BLITZ3GAME_BOOST_MENU_HEADER";
      
      public static const LOC_BOOST_MENU_LQMODE_ACCEPT:String = "LOC_BLITZ3GAME_BOOST_MENU_LQMODE_ACCEPT";
      
      public static const LOC_BOOST_MENU_LQMODE_BODY:String = "LOC_BLITZ3GAME_BOOST_MENU_LQMODE_BODY";
      
      public static const LOC_BOOST_MENU_LQMODE_DECLINE:String = "LOC_BLITZ3GAME_BOOST_MENU_LQMODE_DECLINE";
      
      public static const LOC_BOOST_MENU_LQMODE_TITLE:String = "LOC_BLITZ3GAME_BOOST_MENU_LQMODE_TITLE";
      
      public static const LOC_BOOST_MENU_SUBTITLE_AUTORENEWED:String = "LOC_BLITZ3GAME_BOOST_MENU_SUBTITLE_AUTORENEWED";
      
      public static const LOC_BOOST_MENU_SUBTITLE_CHOOSE_0:String = "LOC_BLITZ3GAME_BOOST_MENU_SUBTITLE_CHOOSE_0";
      
      public static const LOC_BOOST_MENU_SUBTITLE_CHOOSE_1:String = "LOC_BLITZ3GAME_BOOST_MENU_SUBTITLE_CHOOSE_1";
      
      public static const LOC_BOOST_MENU_SUBTITLE_CHOOSE_2:String = "LOC_BLITZ3GAME_BOOST_MENU_SUBTITLE_CHOOSE_2";
      
      public static const LOC_BOOST_MENU_SUBTITLE_CHOOSE_3:String = "LOC_BLITZ3GAME_BOOST_MENU_SUBTITLE_CHOOSE_3";
      
      public static const LOC_BUTTON_ADD_COINS:String = "LOC_BLITZ3GAME_BUTTON_ADD_COINS";
      
      public static const LOC_CHALLENGE_COMPLETED_COLLECT:String = "LOC_BLITZ3GAME_CHALLENGE_COMPLETED_COLLECT";
      
      public static const LOC_CHALLENGE_COMPLETED_COLLECTED:String = "LOC_BLITZ3GAME_CHALLENGE_COMPLETED_COLLECTED";
      
      public static const LOC_CHALLENGE_COMPLETED_COLLECT_BEFORE:String = "LOC_BLITZ3GAME_CHALLENGE_COMPLETED_COLLECT_BEFORE";
      
      public static const LOC_CHALLENGE_COMPLETED_EXPIRES:String = "LOC_BLITZ3GAME_CHALLENGE_COMPLETED_EXPIRES";
      
      public static const LOC_CHALLENGE_CURRENT_ACCEPT_BY:String = "LOC_BLITZ3GAME_CHALLENGE_CURRENT_ACCEPT_BY";
      
      public static const LOC_CHALLENGE_CURRENT_FINALIZE:String = "LOC_BLITZ3GAME_CHALLENGE_CURRENT_FINALIZE";
      
      public static const LOC_CHALLENGE_CURRENT_PLAY:String = "LOC_BLITZ3GAME_CHALLENGE_CURRENT_PLAY";
      
      public static const LOC_CHALLENGE_CURRENT_WAITING_SENT:String = "LOC_BLITZ3GAME_CHALLENGE_CURRENT_WAITING_SENT";
      
      public static const LOC_CHALLENGE_CURRENT_WAITING_SENT_ON:String = "LOC_BLITZ3GAME_CHALLENGE_CURRENT_WAITING_SENT_ON";
      
      public static const LOC_CHALLENGE_DUEL_LABEL:String = "LOC_BLITZ3GAME_CHALLENGE_DUEL_LABEL";
      
      public static const LOC_CHALLENGE_ERROR_PARTY_PACKED_BODY:String = "LOC_BLITZ3GAME_CHALLENGE_ERROR_PARTY_PACKED_BODY";
      
      public static const LOC_CHALLENGE_ERROR_PARTY_PACKED_TITLE:String = "LOC_BLITZ3GAME_CHALLENGE_ERROR_PARTY_PACKED_TITLE";
      
      public static const LOC_CHALLENGE_FEATURE_NOT_FULLY_UNLOCKED:String = "LOC_BLITZ3GAME_CHALLENGE_FEATURE_NOT_FULLY_UNLOCKED";
      
      public static const LOC_CHALLENGE_GOAL_TOOLTIP_FLAME:String = "LOC_BLITZ3GAME_CHALLENGE_GOAL_TOOLTIP_FLAME";
      
      public static const LOC_CHALLENGE_GOAL_TOOLTIP_HYPER:String = "LOC_BLITZ3GAME_CHALLENGE_GOAL_TOOLTIP_HYPER";
      
      public static const LOC_CHALLENGE_GOAL_TOOLTIP_STAR:String = "LOC_BLITZ3GAME_CHALLENGE_GOAL_TOOLTIP_STAR";
      
      public static const LOC_CHALLENGE_LIST_HEADER_COLLECT:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_HEADER_COLLECT";
      
      public static const LOC_CHALLENGE_LIST_HEADER_PLAY:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_HEADER_PLAY";
      
      public static const LOC_CHALLENGE_LIST_HEADER_SENT:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_HEADER_SENT";
      
      public static const LOC_CHALLENGE_LIST_TYPE_COLLECT:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_TYPE_COLLECT";
      
      public static const LOC_CHALLENGE_LIST_TYPE_GAMEOVER:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_TYPE_GAMEOVER";
      
      public static const LOC_CHALLENGE_LIST_TYPE_PLAY:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_TYPE_PLAY";
      
      public static const LOC_CHALLENGE_LIST_TYPE_SENT:String = "LOC_BLITZ3GAME_CHALLENGE_LIST_TYPE_SENT";
      
      public static const LOC_CHALLENGE_NEXT_FREE_GAME_IN:String = "LOC_BLITZ3GAME_CHALLENGE_NEXT_FREE_GAME_IN";
      
      public static const LOC_CHALLENGE_PLAY_BUTTON_RIBBON:String = "LOC_BLITZ3GAME_CHALLENGE_PLAY_BUTTON_RIBBON";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_COINS:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_COINS";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_DESTROY:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_DESTROY";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_ELITE_HELP:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_ELITE_HELP";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_POINTS:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_POINTS";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_TEAM_GOAL:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_TEAM_GOAL";
      
      public static const LOC_CHALLENGE_POPUP_GOAL_WIN_UP_TO:String = "LOC_BLITZ3GAME_CHALLENGE_POPUP_GOAL_WIN_UP_TO";
      
      public static const LOC_CHALLENGE_STATE_SIDE_BOTTOM_MESSAGE:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_BOTTOM_MESSAGE";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_COIN_BONUS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_COIN_BONUS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_HEADER";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_PTS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_PTS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_BACK:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_BACK";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_COINS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_COINS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_COIN_BONUS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_COIN_BONUS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_HEADER";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_PTS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_PTS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_REMATCH:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_REMATCH";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_TOKENS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_TOKENS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_GAME_RESULTS_XP:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_GAME_RESULTS_XP";
      
      public static const LOC_CHALLENGE_STATE_SIDE_LIST_STATUS_BACK:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_LIST_STATUS_BACK";
      
      public static const LOC_CHALLENGE_STATE_SIDE_LIST_STATUS_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_LIST_STATUS_HEADER";
      
      public static const LOC_CHALLENGE_STATE_SIDE_LIST_STATUS_PTS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_LIST_STATUS_PTS";
      
      public static const LOC_CHALLENGE_STATE_SIDE_LIST_STATUS_REMIND:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_SIDE_LIST_STATUS_REMIND";
      
      public static const LOC_CHALLENGE_STATE_STATUS_CONTINUE_BTN:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_CONTINUE_BTN";
      
      public static const LOC_CHALLENGE_STATE_STATUS_FOOTER:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_FOOTER";
      
      public static const LOC_CHALLENGE_STATE_STATUS_FOOTER_P2:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_FOOTER_P2";
      
      public static const LOC_CHALLENGE_STATE_STATUS_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_HEADER";
      
      public static const LOC_CHALLENGE_STATE_STATUS_HEADER_LIMITED:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_HEADER_LIMITED";
      
      public static const LOC_CHALLENGE_STATE_STATUS_POINTS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_POINTS";
      
      public static const LOC_CHALLENGE_STATE_STATUS_QUESTION:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_QUESTION";
      
      public static const LOC_CHALLENGE_STATE_STATUS_QUESTION_0_GOALS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_QUESTION_0_GOALS";
      
      public static const LOC_CHALLENGE_STATE_STATUS_QUESTION_LIMITED:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_QUESTION_LIMITED";
      
      public static const LOC_CHALLENGE_STATE_STATUS_QUESTION_N_GOALS:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_QUESTION_N_GOALS";
      
      public static const LOC_CHALLENGE_STATE_STATUS_QUESTION_PERFECT:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_QUESTION_PERFECT";
      
      public static const LOC_CHALLENGE_STATE_STATUS_REMAINING:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_REMAINING";
      
      public static const LOC_CHALLENGE_STATE_STATUS_SEND_BTN:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_SEND_BTN";
      
      public static const LOC_CHALLENGE_STATE_STATUS_SHARE:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_SHARE";
      
      public static const LOC_CHALLENGE_STATE_STATUS_SHARE_BTN:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_SHARE_BTN";
      
      public static const LOC_CHALLENGE_STATE_STATUS_TRY_AGAIN_BTN:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_TRY_AGAIN_BTN";
      
      public static const LOC_CHALLENGE_STATE_STATUS_WARNING:String = "LOC_BLITZ3GAME_CHALLENGE_STATE_STATUS_WARNING";
      
      public static const LOC_CHALLENGE_STATUS_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_STATUS_HEADER";
      
      public static const LOC_CHALLENGE_STATUS_POINTS:String = "LOC_BLITZ3GAME_CHALLENGE_STATUS_POINTS";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_1:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_1";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_10:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_10";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_2:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_2";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_3:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_3";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_4:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_4";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_4B:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_4B";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_6:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_6";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_6B:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_6B";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_8:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_8";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_9:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_9";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_9B:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_9B";
      
      public static const LOC_CHALLENGE_TUTORIAL_TEXT_9C:String = "LOC_BLITZ3GAME_CHALLENGE_TUTORIAL_TEXT_9C";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_HEADER:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_HEADER";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_NEW_GAMES:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_NEW_GAMES";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_NEW_TO_COLLECT:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_NEW_TO_COLLECT";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_PLAYED_GAMES:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_NO_GAME_NO_PLAYED_GAMES";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_NO_NEW_GAMES:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_NO_NEW_GAMES";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_TAB_COLLECT:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_TAB_COLLECT";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_TAB_PLAY:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_TAB_PLAY";
      
      public static const LOC_CHALLENGE_VIEW_SIDE_LIST_TAB_SENT:String = "LOC_BLITZ3GAME_CHALLENGE_VIEW_SIDE_LIST_TAB_SENT";
      
      public static const LOC_CHALLENGE_WIN_ANIM_BUTTON_CONTINUE:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_BUTTON_CONTINUE";
      
      public static const LOC_CHALLENGE_WIN_ANIM_CONSOLATION:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_CONSOLATION";
      
      public static const LOC_CHALLENGE_WIN_ANIM_EPIC_SCORE:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_EPIC_SCORE";
      
      public static const LOC_CHALLENGE_WIN_ANIM_MAX_SCORE:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_MAX_SCORE";
      
      public static const LOC_CHALLENGE_WIN_ANIM_NICE_TRY:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_NICE_TRY";
      
      public static const LOC_CHALLENGE_WIN_ANIM_YOU_WON:String = "LOC_BLITZ3GAME_CHALLENGE_WIN_ANIM_YOU_WON";
      
      public static const LOC_COINS_TOOLTIP:String = "LOC_BLITZ3GAME_COINS_TOOLTIP";
      
      public static const LOC_COUNT_DOWN_CONTINUE_BTN:String = "LOC_BLITZ3GAME_COUNT_DOWN_CONTINUE_BTN";
      
      public static const LOC_CRASH_DIALOG_BUTTON:String = "LOC_BLITZ3GAME_CRASH_DIALOG_BUTTON";
      
      public static const LOC_CRASH_DIALOG_DESC:String = "LOC_BLITZ3GAME_CRASH_DIALOG_DESC";
      
      public static const LOC_CRASH_DIALOG_TITLE:String = "LOC_BLITZ3GAME_CRASH_DIALOG_TITLE";
      
      public static const LOC_DIALOG_DONT_SHOW_AGAIN:String = "LOC_BLITZ3GAME_DIALOG_DONT_SHOW_AGAIN";
      
      public static const LOC_DIAMONDS_TOOLTIP:String = "LOC_BLITZ3GAME_DIAMONDS_TOOLTIP";
      
      public static const LOC_EC_NO_INTERNET:String = "LOC_BLITZ3GAME_EC_NO_INTERNET";
      
      public static const LOC_EC_REFRESH_BUTTON:String = "LOC_BLITZ3GAME_EC_REFRESH_BUTTON";
      
      public static const LOC_EC_RETRY_BUTTON:String = "LOC_BLITZ3GAME_EC_RETRY_BUTTON";
      
      public static const LOC_EC_SERVER_COMMUNICATION:String = "LOC_BLITZ3GAME_EC_SERVER_COMMUNICATION";
      
      public static const LOC_EC_SERVER_COMMUNICATION_RETRY:String = "LOC_BLITZ3GAME_EC_SERVER_COMMUNICATION_RETRY";
      
      public static const LOC_FEATURE_UNLOCK_FRIEND_SCORE_TITLE:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_FRIEND_SCORE_TITLE";
      
      public static const LOC_FEATURE_UNLOCK_LEADERBOARD_TITLE:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_LEADERBOARD_TITLE";
      
      public static const LOC_FEATURE_UNLOCK_SKIP_BODY:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_SKIP_BODY";
      
      public static const LOC_FEATURE_UNLOCK_SKIP_CONFIRM:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_SKIP_CONFIRM";
      
      public static const LOC_FEATURE_UNLOCK_SKIP_DENY:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_SKIP_DENY";
      
      public static const LOC_FEATURE_UNLOCK_SKIP_TITLE:String = "LOC_BLITZ3GAME_FEATURE_UNLOCK_SKIP_TITLE";
      
      public static const LOC_GAMEPLAY_BONUS_SPEED:String = "LOC_BLITZ3GAME_GAMEPLAY_BONUS_SPEED";
      
      public static const LOC_GEM_COLOR_ANY:String = "LOC_BLITZ3GAME_GEM_COLOR_ANY";
      
      public static const LOC_GEM_COLOR_BLUE:String = "LOC_BLITZ3GAME_GEM_COLOR_BLUE";
      
      public static const LOC_GEM_COLOR_GREEN:String = "LOC_BLITZ3GAME_GEM_COLOR_GREEN";
      
      public static const LOC_GEM_COLOR_ORANGE:String = "LOC_BLITZ3GAME_GEM_COLOR_ORANGE";
      
      public static const LOC_GEM_COLOR_PURPLE:String = "LOC_BLITZ3GAME_GEM_COLOR_PURPLE";
      
      public static const LOC_GEM_COLOR_RED:String = "LOC_BLITZ3GAME_GEM_COLOR_RED";
      
      public static const LOC_GEM_COLOR_WHITE:String = "LOC_BLITZ3GAME_GEM_COLOR_WHITE";
      
      public static const LOC_GEM_COLOR_YELLOW:String = "LOC_BLITZ3GAME_GEM_COLOR_YELLOW";
      
      public static const LOC_GOLDBARS_TOOLTIP:String = "LOC_BLITZ3GAME_GOLDBARS_TOOLTIP";
      
      public static const LOC_HIGHSCORE_ONLINE:String = "LOC_BLITZ3GAME_HIGHSCORE_ONLINE";
      
      public static const LOC_INVITE_TEXT:String = "LOC_BLITZ3GAME_INVITE_TEXT";
      
      public static const LOC_LEVEL_BAR_XP_REMAINING:String = "LOC_BLITZ3GAME_LEVEL_BAR_XP_REMAINING";
      
      public static const LOC_LEVEL_BAR_XP_REMAINING_DISABLED:String = "LOC_BLITZ3GAME_LEVEL_BAR_XP_REMAINING_DISABLED";
      
      public static const LOC_LEVEL_NAME_DISABLED:String = "LOC_BLITZ3GAME_LEVEL_NAME_DISABLED";
      
      public static const LOC_LEVEL_UP_BODY_MYSTERY_TREASURE:String = "LOC_BLITZ3GAME_LEVEL_UP_BODY_MYSTERY_TREASURE";
      
      public static const LOC_LEVEL_UP_BTN_CLAIM:String = "LOC_BLITZ3GAME_LEVEL_UP_BTN_CLAIM";
      
      public static const LOC_LEVEL_UP_BTN_CONTINUE:String = "LOC_BLITZ3GAME_LEVEL_UP_BTN_CONTINUE";
      
      public static const LOC_LEVEL_UP_REWARD_GRAND_TREASURE:String = "LOC_BLITZ3GAME_LEVEL_UP_REWARD_GRAND_TREASURE";
      
      public static const LOC_LEVEL_UP_REWARD_LEGENDARY_TREASURE:String = "LOC_BLITZ3GAME_LEVEL_UP_REWARD_LEGENDARY_TREASURE";
      
      public static const LOC_LEVEL_UP_TITLE:String = "LOC_BLITZ3GAME_LEVEL_UP_TITLE";
      
      public static const LOC_LEVEL_UP_TITLE_10:String = "LOC_BLITZ3GAME_LEVEL_UP_TITLE_10";
      
      public static const LOC_MAIN_MENU_MULTI:String = "LOC_BLITZ3GAME_MAIN_MENU_MULTI";
      
      public static const LOC_MAIN_MENU_PLAY:String = "LOC_BLITZ3GAME_MAIN_MENU_PLAY";
      
      public static const LOC_MAIN_MENU_QUALITY_BODY:String = "LOC_BLITZ3GAME_MAIN_MENU_QUALITY_BODY";
      
      public static const LOC_MAIN_MENU_QUALITY_HIGH:String = "LOC_BLITZ3GAME_MAIN_MENU_QUALITY_HIGH";
      
      public static const LOC_MAIN_MENU_QUALITY_LOW:String = "LOC_BLITZ3GAME_MAIN_MENU_QUALITY_LOW";
      
      public static const LOC_MAIN_MENU_SOLO:String = "LOC_BLITZ3GAME_MAIN_MENU_SOLO";
      
      public static const LOC_NEG_BALANCE_ACCEPT:String = "LOC_BLITZ3GAME_NEG_BALANCE_ACCEPT";
      
      public static const LOC_NEG_BALANCE_BODY:String = "LOC_BLITZ3GAME_NEG_BALANCE_BODY";
      
      public static const LOC_NEG_BALANCE_DECLINE:String = "LOC_BLITZ3GAME_NEG_BALANCE_DECLINE";
      
      public static const LOC_NEG_BALANCE_TITLE:String = "LOC_BLITZ3GAME_NEG_BALANCE_TITLE";
      
      public static const LOC_NEG_BALANCE_TOKENS_ACCEPT:String = "LOC_BLITZ3GAME_NEG_BALANCE_TOKENS_ACCEPT";
      
      public static const LOC_NEG_BALANCE_TOKENS_BODY:String = "LOC_BLITZ3GAME_NEG_BALANCE_TOKENS_BODY";
      
      public static const LOC_NEG_BALANCE_TOKENS_DECLINE:String = "LOC_BLITZ3GAME_NEG_BALANCE_TOKENS_DECLINE";
      
      public static const LOC_NEG_BALANCE_TOKENS_TITLE:String = "LOC_BLITZ3GAME_NEG_BALANCE_TOKENS_TITLE";
      
      public static const LOC_NUM_UPSELLS:String = "LOC_BLITZ3GAME_NUM_UPSELLS";
      
      public static const LOC_OPTIONS_AUTO_HINT:String = "LOC_BLITZ3GAME_OPTIONS_AUTO_HINT";
      
      public static const LOC_OPTIONS_AUTO_RENEW:String = "LOC_BLITZ3GAME_OPTIONS_AUTO_RENEW";
      
      public static const LOC_OPTIONS_AUTO_RENEW_BODY:String = "LOC_BLITZ3GAME_OPTIONS_AUTO_RENEW_BODY";
      
      public static const LOC_OPTIONS_CHANGE_QUALITY_BODY:String = "LOC_BLITZ3GAME_OPTIONS_CHANGE_QUALITY_BODY";
      
      public static const LOC_OPTIONS_CHANGE_QUALITY_BODY_CHECK:String = "LOC_BLITZ3GAME_OPTIONS_CHANGE_QUALITY_BODY_CHECK";
      
      public static const LOC_OPTIONS_CHANGE_QUALITY_HIGH:String = "LOC_BLITZ3GAME_OPTIONS_CHANGE_QUALITY_HIGH";
      
      public static const LOC_OPTIONS_CHANGE_QUALITY_LOW:String = "LOC_BLITZ3GAME_OPTIONS_CHANGE_QUALITY_LOW";
      
      public static const LOC_OPTIONS_CLOSE:String = "LOC_BLITZ3GAME_OPTIONS_CLOSE";
      
      public static const LOC_OPTIONS_CONFIRM_CHANGE_QUALITY:String = "LOC_BLITZ3GAME_OPTIONS_CONFIRM_CHANGE_QUALITY";
      
      public static const LOC_OPTIONS_HELP:String = "LOC_BLITZ3GAME_OPTIONS_HELP";
      
      public static const LOC_OPTIONS_SOUND:String = "LOC_BLITZ3GAME_OPTIONS_SOUND";
      
      public static const LOC_OPTIONS_TITLE:String = "LOC_BLITZ3GAME_OPTIONS_TITLE";
      
      public static const LOC_PAUSE_CHANGE_QUALITY:String = "LOC_BLITZ3GAME_PAUSE_CHANGE_QUALITY";
      
      public static const LOC_PAUSE_CLOSE:String = "LOC_BLITZ3GAME_PAUSE_CLOSE";
      
      public static const LOC_PAUSE_MAINBTN_CONFIRM_CONFIRM:String = "LOC_BLITZ3GAME_PAUSE_MAINBTN_CONFIRM_CONFIRM";
      
      public static const LOC_PAUSE_MAINBTN_CONFIRM_DECLINE:String = "LOC_BLITZ3GAME_PAUSE_MAINBTN_CONFIRM_DECLINE";
      
      public static const LOC_PAUSE_MAINBTN_CONFIRM_DETAILS:String = "LOC_BLITZ3GAME_PAUSE_MAINBTN_CONFIRM_DETAILS";
      
      public static const LOC_PAUSE_MAINBTN_CONFIRM_TITLE:String = "LOC_BLITZ3GAME_PAUSE_MAINBTN_CONFIRM_TITLE";
      
      public static const LOC_PAUSE_OPTIONS:String = "LOC_BLITZ3GAME_PAUSE_OPTIONS";
      
      public static const LOC_PAUSE_RESET:String = "LOC_BLITZ3GAME_PAUSE_RESET";
      
      public static const LOC_PAUSE_RESET_CONFIRM_CONFIRM:String = "LOC_BLITZ3GAME_PAUSE_RESET_CONFIRM_CONFIRM";
      
      public static const LOC_PAUSE_RESET_CONFIRM_DECLINE:String = "LOC_BLITZ3GAME_PAUSE_RESET_CONFIRM_DECLINE";
      
      public static const LOC_PAUSE_RESET_CONFIRM_TITLE:String = "LOC_BLITZ3GAME_PAUSE_RESET_CONFIRM_TITLE";
      
      public static const LOC_PAUSE_TITLE:String = "LOC_BLITZ3GAME_PAUSE_TITLE";
      
      public static const LOC_PHOENIX_PRISM_BONUS:String = "LOC_BLITZ3GAME_PHOENIX_PRISM_BONUS";
      
      public static const LOC_PHOENIX_PRISM_BONUS_SHARE_CONFIRM:String = "LOC_BLITZ3GAME_PHOENIX_PRISM_BONUS_SHARE_CONFIRM";
      
      public static const LOC_PHOENIX_PRISM_BONUS_SHARE_DECLINE:String = "LOC_BLITZ3GAME_PHOENIX_PRISM_BONUS_SHARE_DECLINE";
      
      public static const LOC_PHOENIX_PRISM_BONUS_SHARE_MESSAGE:String = "LOC_BLITZ3GAME_PHOENIX_PRISM_BONUS_SHARE_MESSAGE";
      
      public static const LOC_PHOENIX_PRISM_BONUS_SHARE_TITLE:String = "LOC_BLITZ3GAME_PHOENIX_PRISM_BONUS_SHARE_TITLE";
      
      public static const LOC_PLAY_MORE_TO_UNLOCK:String = "LOC_BLITZ3GAME_PLAY_MORE_TO_UNLOCK";
      
      public static const LOC_POKE_TEXT:String = "LOC_BLITZ3GAME_POKE_TEXT";
      
      public static const LOC_QUEST_COMPOUND_SEPARATOR:String = "LOC_BLITZ3GAME_QUEST_COMPOUND_SEPARATOR";
      
      public static const LOC_QUEST_CONTINUE:String = "LOC_BLITZ3GAME_QUEST_CONTINUE";
      
      public static const LOC_QUEST_EXPIRARY_DAY:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_DAY";
      
      public static const LOC_QUEST_EXPIRARY_DAY_SINGULAR:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_DAY_SINGULAR";
      
      public static const LOC_QUEST_EXPIRARY_EXPIRED:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_EXPIRED";
      
      public static const LOC_QUEST_EXPIRARY_HOUR:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_HOUR";
      
      public static const LOC_QUEST_EXPIRARY_HOUR_SINGULAR:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_HOUR_SINGULAR";
      
      public static const LOC_QUEST_EXPIRARY_HURRY:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_HURRY";
      
      public static const LOC_QUEST_EXPIRARY_LAST_CHANCE:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_LAST_CHANCE";
      
      public static const LOC_QUEST_EXPIRARY_MINS:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_MINS";
      
      public static const LOC_QUEST_EXPIRARY_MINS_SINGULAR:String = "LOC_BLITZ3GAME_QUEST_EXPIRARY_MINS_SINGULAR";
      
      public static const LOC_QUEST_EXTENDED_REWARD_BOOSTS:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_BOOSTS";
      
      public static const LOC_QUEST_EXTENDED_REWARD_DAILY_SPIN:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_DAILY_SPIN";
      
      public static const LOC_QUEST_EXTENDED_REWARD_FRIENDSCORE:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_FRIENDSCORE";
      
      public static const LOC_QUEST_EXTENDED_REWARD_LEADERBOARD_BASIC:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_LEADERBOARD_BASIC";
      
      public static const LOC_QUEST_EXTENDED_REWARD_LEVELS:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_LEVELS";
      
      public static const LOC_QUEST_EXTENDED_REWARD_MULTIPLAYER:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_MULTIPLAYER";
      
      public static const LOC_QUEST_EXTENDED_REWARD_QUEST_WIDGET:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_QUEST_WIDGET";
      
      public static const LOC_QUEST_EXTENDED_REWARD_RARE_GEMS:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_RARE_GEMS";
      
      public static const LOC_QUEST_EXTENDED_REWARD_STAR_MEDAL:String = "LOC_BLITZ3GAME_QUEST_EXTENDED_REWARD_STAR_MEDAL";
      
      public static const LOC_QUEST_GAME_OVER_CLAIM_NOW:String = "LOC_BLITZ3GAME_QUEST_GAME_OVER_CLAIM_NOW";
      
      public static const LOC_QUEST_GAME_OVER_REWARD_CENTER:String = "LOC_BLITZ3GAME_QUEST_GAME_OVER_REWARD_CENTER";
      
      public static const LOC_QUEST_GAME_OVER_TITLE:String = "LOC_BLITZ3GAME_QUEST_GAME_OVER_TITLE";
      
      public static const LOC_QUEST_REWARD_BOOSTS:String = "LOC_BLITZ3GAME_QUEST_REWARD_BOOSTS";
      
      public static const LOC_QUEST_REWARD_DAILY_SPIN:String = "LOC_BLITZ3GAME_QUEST_REWARD_DAILY_SPIN";
      
      public static const LOC_QUEST_REWARD_FRIENDSCORE:String = "LOC_BLITZ3GAME_QUEST_REWARD_FRIENDSCORE";
      
      public static const LOC_QUEST_REWARD_LEADERBOARD_BASIC:String = "LOC_BLITZ3GAME_QUEST_REWARD_LEADERBOARD_BASIC";
      
      public static const LOC_QUEST_REWARD_LEVELS:String = "LOC_BLITZ3GAME_QUEST_REWARD_LEVELS";
      
      public static const LOC_QUEST_REWARD_MULTIPLAYER:String = "LOC_BLITZ3GAME_QUEST_REWARD_MULTIPLAYER";
      
      public static const LOC_QUEST_REWARD_PANEL_BLAZINGSTEED:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_BLAZINGSTEED";
      
      public static const LOC_QUEST_REWARD_PANEL_CATSEYE:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_CATSEYE";
      
      public static const LOC_QUEST_REWARD_PANEL_FIREWORKS:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_FIREWORKS";
      
      public static const LOC_QUEST_REWARD_PANEL_KANGARUBY1:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_KANGARUBY1";
      
      public static const LOC_QUEST_REWARD_PANEL_KANGARUBY2:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_KANGARUBY2";
      
      public static const LOC_QUEST_REWARD_PANEL_KANGARUBY3:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_KANGARUBY3";
      
      public static const LOC_QUEST_REWARD_PANEL_MOONSTONE:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_MOONSTONE";
      
      public static const LOC_QUEST_REWARD_PANEL_PHOENIXPRISM:String = "LOC_BLITZ3GAME_QUEST_REWARD_PANEL_PHOENIXPRISM";
      
      public static const LOC_QUEST_REWARD_RARE_GEMS:String = "LOC_BLITZ3GAME_QUEST_REWARD_RARE_GEMS";
      
      public static const LOC_QUEST_REWARD_STAR_MEDALS:String = "LOC_BLITZ3GAME_QUEST_REWARD_STAR_MEDALS";
      
      public static const LOC_QUEST_REWARD_WIDGET_CONGRATS:String = "LOC_BLITZ3GAME_QUEST_REWARD_WIDGET_CONGRATS";
      
      public static const LOC_QUEST_REWARD_WIDGET_UNLOCKED:String = "LOC_BLITZ3GAME_QUEST_REWARD_WIDGET_UNLOCKED";
      
      public static const LOC_QUEST_SCREEN_MYSTERY_RARE_GEM:String = "LOC_BLITZ3GAME_QUEST_SCREEN_MYSTERY_RARE_GEM";
      
      public static const LOC_QUEST_SCREEN_TITLE_ALL:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_ALL";
      
      public static const LOC_QUEST_SCREEN_TITLE_BOOSTS:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_BOOSTS";
      
      public static const LOC_QUEST_SCREEN_TITLE_DAILY_SPIN:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_DAILY_SPIN";
      
      public static const LOC_QUEST_SCREEN_TITLE_FRIEND_SCORE:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_FRIEND_SCORE";
      
      public static const LOC_QUEST_SCREEN_TITLE_KEYSTONES:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_KEYSTONES";
      
      public static const LOC_QUEST_SCREEN_TITLE_LEADERBOARD:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_LEADERBOARD";
      
      public static const LOC_QUEST_SCREEN_TITLE_RARE_GEMS:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_RARE_GEMS";
      
      public static const LOC_QUEST_SCREEN_TITLE_STAR_MEDALS:String = "LOC_BLITZ3GAME_QUEST_SCREEN_TITLE_STAR_MEDALS";
      
      public static const LOC_QUEST_TOOL_TIP_BODY:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_BODY";
      
      public static const LOC_QUEST_TOOL_TIP_BODY_LOCKED:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_BODY_LOCKED";
      
      public static const LOC_QUEST_TOOL_TIP_BODY_NOT_APPLICABLE:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_BODY_NOT_APPLICABLE";
      
      public static const LOC_QUEST_TOOL_TIP_TITLE_EASY:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_TITLE_EASY";
      
      public static const LOC_QUEST_TOOL_TIP_TITLE_HARD:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_TITLE_HARD";
      
      public static const LOC_QUEST_TOOL_TIP_TITLE_MEDIUM:String = "LOC_BLITZ3GAME_QUEST_TOOL_TIP_TITLE_MEDIUM";
      
      public static const LOC_QUEST_WIDGET_COMPLETED:String = "LOC_BLITZ3GAME_QUEST_WIDGET_COMPLETED";
      
      public static const LOC_QUEST_WIDGET_NEW:String = "LOC_BLITZ3GAME_QUEST_WIDGET_NEW";
      
      public static const LOC_QUEST_WIDGET_UNLOCK_SEPARATOR:String = "LOC_BLITZ3GAME_QUEST_WIDGET_UNLOCK_SEPARATOR";
      
      public static const LOC_REPLAY_CLOSE_BTN:String = "LOC_BLITZ3GAME_REPLAY_CLOSE_BTN";
      
      public static const LOC_REPLAY_CLOSE_DESC:String = "LOC_BLITZ3GAME_REPLAY_CLOSE_DESC";
      
      public static const LOC_REPLAY_CLOSE_TITLE:String = "LOC_BLITZ3GAME_REPLAY_CLOSE_TITLE";
      
      public static const LOC_REPLAY_CONTINUE_BTN:String = "LOC_BLITZ3GAME_REPLAY_CONTINUE_BTN";
      
      public static const LOC_REPLAY_END_DESC:String = "LOC_BLITZ3GAME_REPLAY_END_DESC";
      
      public static const LOC_REPLAY_END_TITLE:String = "LOC_BLITZ3GAME_REPLAY_END_TITLE";
      
      public static const LOC_REPLAY_ERROR_BTN:String = "LOC_BLITZ3GAME_REPLAY_ERROR_BTN";
      
      public static const LOC_REPLAY_ERROR_DESC:String = "LOC_BLITZ3GAME_REPLAY_ERROR_DESC";
      
      public static const LOC_REPLAY_ERROR_TITLE:String = "LOC_BLITZ3GAME_REPLAY_ERROR_TITLE";
      
      public static const LOC_REPLAY_RESUME_BTN:String = "LOC_BLITZ3GAME_REPLAY_RESUME_BTN";
      
      public static const LOC_RG_ACTIVATED_BLAZINGSTEED:String = "LOC_BLITZ3GAME_RG_ACTIVATED_BLAZINGSTEED";
      
      public static const LOC_RG_ACTIVATED_CATSEYE:String = "LOC_BLITZ3GAME_RG_ACTIVATED_CATSEYE";
      
      public static const LOC_RG_ACTIVATED_FIREWORKS:String = "LOC_BLITZ3GAME_RG_ACTIVATED_FIREWORKS";
      
      public static const LOC_RG_ACTIVATED_KANGARUBY:String = "LOC_BLITZ3GAME_RG_ACTIVATED_KANGARUBY";
      
      public static const LOC_RG_ACTIVATED_KANGARUBY2:String = "LOC_BLITZ3GAME_RG_ACTIVATED_KANGARUBY2";
      
      public static const LOC_RG_ACTIVATED_KANGARUBY3:String = "LOC_BLITZ3GAME_RG_ACTIVATED_KANGARUBY3";
      
      public static const LOC_RG_ACTIVATED_MOONSTONE:String = "LOC_BLITZ3GAME_RG_ACTIVATED_MOONSTONE";
      
      public static const LOC_RG_ACTIVATED_PHOENIXPRISM:String = "LOC_BLITZ3GAME_RG_ACTIVATED_PHOENIXPRISM";
      
      public static const LOC_RG_BLAZINGSTEED:String = "LOC_BLITZ3GAME_RG_BLAZINGSTEED";
      
      public static const LOC_RG_BTN_ACCEPT:String = "LOC_BLITZ3GAME_RG_BTN_ACCEPT";
      
      public static const LOC_RG_BTN_DECLINE:String = "LOC_BLITZ3GAME_RG_BTN_DECLINE";
      
      public static const LOC_RG_CATSEYE:String = "LOC_BLITZ3GAME_RG_CATSEYE";
      
      public static const LOC_RG_COPY_BLAZINGSTEED:String = "LOC_BLITZ3GAME_RG_COPY_BLAZINGSTEED";
      
      public static const LOC_RG_COPY_BLAZINGSTEED_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_BLAZINGSTEED_STREAK1";
      
      public static const LOC_RG_COPY_BLAZINGSTEED_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_BLAZINGSTEED_STREAK2";
      
      public static const LOC_RG_COPY_BLAZINGSTEED_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_BLAZINGSTEED_STREAK3";
      
      public static const LOC_RG_COPY_CATSEYE:String = "LOC_BLITZ3GAME_RG_COPY_CATSEYE";
      
      public static const LOC_RG_COPY_CATSEYE_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_CATSEYE_STREAK1";
      
      public static const LOC_RG_COPY_CATSEYE_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_CATSEYE_STREAK2";
      
      public static const LOC_RG_COPY_CATSEYE_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_CATSEYE_STREAK3";
      
      public static const LOC_RG_COPY_DISCOUNT_BLAZINGSTEED:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_BLAZINGSTEED";
      
      public static const LOC_RG_COPY_DISCOUNT_CATSEYE:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_CATSEYE";
      
      public static const LOC_RG_COPY_DISCOUNT_FIREWORKS:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_FIREWORKS";
      
      public static const LOC_RG_COPY_DISCOUNT_KANGARUBY:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_KANGARUBY";
      
      public static const LOC_RG_COPY_DISCOUNT_KANGARUBY2:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_KANGARUBY2";
      
      public static const LOC_RG_COPY_DISCOUNT_KANGARUBY3:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_KANGARUBY3";
      
      public static const LOC_RG_COPY_DISCOUNT_MOONSTONE:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_MOONSTONE";
      
      public static const LOC_RG_COPY_DISCOUNT_PHOENIXPRISM:String = "LOC_BLITZ3GAME_RG_COPY_DISCOUNT_PHOENIXPRISM";
      
      public static const LOC_RG_COPY_FIREWORKS:String = "LOC_BLITZ3GAME_RG_COPY_FIREWORKS";
      
      public static const LOC_RG_COPY_FIREWORKS_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_FIREWORKS_STREAK1";
      
      public static const LOC_RG_COPY_FIREWORKS_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_FIREWORKS_STREAK2";
      
      public static const LOC_RG_COPY_FIREWORKS_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_FIREWORKS_STREAK3";
      
      public static const LOC_RG_COPY_KANGARUBY:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY";
      
      public static const LOC_RG_COPY_KANGARUBY2:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY2";
      
      public static const LOC_RG_COPY_KANGARUBY2_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY2_STREAK1";
      
      public static const LOC_RG_COPY_KANGARUBY2_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY2_STREAK2";
      
      public static const LOC_RG_COPY_KANGARUBY2_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY2_STREAK3";
      
      public static const LOC_RG_COPY_KANGARUBY3:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY3";
      
      public static const LOC_RG_COPY_KANGARUBY3_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY3_STREAK1";
      
      public static const LOC_RG_COPY_KANGARUBY3_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY3_STREAK2";
      
      public static const LOC_RG_COPY_KANGARUBY3_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY3_STREAK3";
      
      public static const LOC_RG_COPY_KANGARUBY_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY_STREAK1";
      
      public static const LOC_RG_COPY_KANGARUBY_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY_STREAK2";
      
      public static const LOC_RG_COPY_KANGARUBY_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_KANGARUBY_STREAK3";
      
      public static const LOC_RG_COPY_MOONSTONE:String = "LOC_BLITZ3GAME_RG_COPY_MOONSTONE";
      
      public static const LOC_RG_COPY_MOONSTONE_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_MOONSTONE_STREAK1";
      
      public static const LOC_RG_COPY_MOONSTONE_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_MOONSTONE_STREAK2";
      
      public static const LOC_RG_COPY_MOONSTONE_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_MOONSTONE_STREAK3";
      
      public static const LOC_RG_COPY_PHOENIXPRISM:String = "LOC_BLITZ3GAME_RG_COPY_PHOENIXPRISM";
      
      public static const LOC_RG_COPY_PHOENIXPRISM_STREAK1:String = "LOC_BLITZ3GAME_RG_COPY_PHOENIXPRISM_STREAK1";
      
      public static const LOC_RG_COPY_PHOENIXPRISM_STREAK2:String = "LOC_BLITZ3GAME_RG_COPY_PHOENIXPRISM_STREAK2";
      
      public static const LOC_RG_COPY_PHOENIXPRISM_STREAK3:String = "LOC_BLITZ3GAME_RG_COPY_PHOENIXPRISM_STREAK3";
      
      public static const LOC_RG_COST_TEXT:String = "LOC_BLITZ3GAME_RG_COST_TEXT";
      
      public static const LOC_RG_COST_TEXT_DISCOUNT:String = "LOC_BLITZ3GAME_RG_COST_TEXT_DISCOUNT";
      
      public static const LOC_RG_COST_TEXT_STREAK1:String = "LOC_BLITZ3GAME_RG_COST_TEXT_STREAK1";
      
      public static const LOC_RG_COST_TEXT_STREAK2:String = "LOC_BLITZ3GAME_RG_COST_TEXT_STREAK2";
      
      public static const LOC_RG_COST_TEXT_STREAK3:String = "LOC_BLITZ3GAME_RG_COST_TEXT_STREAK3";
      
      public static const LOC_RG_FIREWORKS:String = "LOC_BLITZ3GAME_RG_FIREWORKS";
      
      public static const LOC_RG_KANGARUBY:String = "LOC_BLITZ3GAME_RG_KANGARUBY";
      
      public static const LOC_RG_KANGARUBY2:String = "LOC_BLITZ3GAME_RG_KANGARUBY2";
      
      public static const LOC_RG_KANGARUBY3:String = "LOC_BLITZ3GAME_RG_KANGARUBY3";
      
      public static const LOC_RG_MOONSTONE:String = "LOC_BLITZ3GAME_RG_MOONSTONE";
      
      public static const LOC_RG_PHOENIXPRISM:String = "LOC_BLITZ3GAME_RG_PHOENIXPRISM";
      
      public static const LOC_RG_STREAK_CONTINUE:String = "LOC_BLITZ3GAME_RG_STREAK_CONTINUE";
      
      public static const LOC_RG_STREAK_LARGE_MESSAGE:String = "LOC_BLITZ3GAME_RG_STREAK_LARGE_MESSAGE";
      
      public static const LOC_RG_STREAK_SMALL_MESSAGE:String = "LOC_BLITZ3GAME_RG_STREAK_SMALL_MESSAGE";
      
      public static const LOC_RG_TITLE:String = "LOC_BLITZ3GAME_RG_TITLE";
      
      public static const LOC_RG_TITLE_DISCOUNT:String = "LOC_BLITZ3GAME_RG_TITLE_DISCOUNT";
      
      public static const LOC_RG_TITLE_STREAK1:String = "LOC_BLITZ3GAME_RG_TITLE_STREAK1";
      
      public static const LOC_RG_TITLE_STREAK2:String = "LOC_BLITZ3GAME_RG_TITLE_STREAK2";
      
      public static const LOC_RG_TITLE_STREAK3:String = "LOC_BLITZ3GAME_RG_TITLE_STREAK3";
      
      public static const LOC_SHARDS_TOOLTIP:String = "LOC_BLITZ3GAME_SHARDS_TOOLTIP";
      
      public static const LOC_THOUSAND_SEP:String = "LOC_BLITZ3GAME_THOUSAND_SEP";
      
      public static const LOC_THOUSAND_UNIT:String = "LOC_BLITZ3GAME_THOUSAND_UNIT";
      
      public static const LOC_TIME_AM:String = "LOC_BLITZ3GAME_TIME_AM";
      
      public static const LOC_TIME_PM:String = "LOC_BLITZ3GAME_TIME_PM";
      
      public static const LOC_TIP_TEXT:String = "LOC_BLITZ3GAME_TIP_TEXT";
      
      public static const LOC_TOKENS_TOOLTIP:String = "LOC_BLITZ3GAME_TOKENS_TOOLTIP";
      
      public static const LOC_TUTORIAL_1_SWAP:String = "LOC_BLITZ3GAME_TUTORIAL_1_SWAP";
      
      public static const LOC_TUTORIAL_1_SWAP_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_1_SWAP_TITLE";
      
      public static const LOC_TUTORIAL_CONFIRM_BODY:String = "LOC_BLITZ3GAME_TUTORIAL_CONFIRM_BODY";
      
      public static const LOC_TUTORIAL_CONFIRM_CONFIRM:String = "LOC_BLITZ3GAME_TUTORIAL_CONFIRM_CONFIRM";
      
      public static const LOC_TUTORIAL_CONFIRM_DECLINE:String = "LOC_BLITZ3GAME_TUTORIAL_CONFIRM_DECLINE";
      
      public static const LOC_TUTORIAL_CONFIRM_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_CONFIRM_TITLE";
      
      public static const LOC_TUTORIAL_CONGRATS:String = "LOC_BLITZ3GAME_TUTORIAL_CONGRATS";
      
      public static const LOC_TUTORIAL_CONTINUE:String = "LOC_BLITZ3GAME_TUTORIAL_CONTINUE";
      
      public static const LOC_TUTORIAL_CONTINUE_TO_GAME:String = "LOC_BLITZ3GAME_TUTORIAL_CONTINUE_TO_GAME";
      
      public static const LOC_TUTORIAL_DISABLE_TIPS:String = "LOC_BLITZ3GAME_TUTORIAL_DISABLE_TIPS";
      
      public static const LOC_TUTORIAL_FEATURES_UNLOCKED:String = "LOC_BLITZ3GAME_TUTORIAL_FEATURES_UNLOCKED";
      
      public static const LOC_TUTORIAL_FINISH:String = "LOC_BLITZ3GAME_TUTORIAL_FINISH";
      
      public static const LOC_TUTORIAL_FLAME_GEM_CREATE:String = "LOC_BLITZ3GAME_TUTORIAL_FLAME_GEM_CREATE";
      
      public static const LOC_TUTORIAL_FLAME_GEM_CREATE_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_FLAME_GEM_CREATE_TITLE";
      
      public static const LOC_TUTORIAL_FLAME_GEM_MATCH:String = "LOC_BLITZ3GAME_TUTORIAL_FLAME_GEM_MATCH";
      
      public static const LOC_TUTORIAL_FLAME_GEM_MATCH_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_FLAME_GEM_MATCH_TITLE";
      
      public static const LOC_TUTORIAL_HINT_BUTTON:String = "LOC_BLITZ3GAME_TUTORIAL_HINT_BUTTON";
      
      public static const LOC_TUTORIAL_HINT_BUTTON_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_HINT_BUTTON_TITLE";
      
      public static const LOC_TUTORIAL_N_SWAPS:String = "LOC_BLITZ3GAME_TUTORIAL_N_SWAPS";
      
      public static const LOC_TUTORIAL_N_SWAPS_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_N_SWAPS_TITLE";
      
      public static const LOC_TUTORIAL_PAGES:String = "LOC_BLITZ3GAME_TUTORIAL_PAGES";
      
      public static const LOC_TUTORIAL_REPLAY:String = "LOC_BLITZ3GAME_TUTORIAL_REPLAY";
      
      public static const LOC_TUTORIAL_SKIP:String = "LOC_BLITZ3GAME_TUTORIAL_SKIP";
      
      public static const LOC_TUTORIAL_START:String = "LOC_BLITZ3GAME_TUTORIAL_START";
      
      public static const LOC_TUTORIAL_SUBTITLE:String = "LOC_BLITZ3GAME_TUTORIAL_SUBTITLE";
      
      public static const LOC_TUTORIAL_SWAP_HORIZONTAL:String = "LOC_BLITZ3GAME_TUTORIAL_SWAP_HORIZONTAL";
      
      public static const LOC_TUTORIAL_SWAP_HORIZONTAL_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_SWAP_HORIZONTAL_TITLE";
      
      public static const LOC_TUTORIAL_SWAP_VERTICALLY:String = "LOC_BLITZ3GAME_TUTORIAL_SWAP_VERTICALLY";
      
      public static const LOC_TUTORIAL_SWAP_VERTICALLY_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_SWAP_VERTICALLY_TITLE";
      
      public static const LOC_TUTORIAL_TIMER:String = "LOC_BLITZ3GAME_TUTORIAL_TIMER";
      
      public static const LOC_TUTORIAL_TIMER_TITLE:String = "LOC_BLITZ3GAME_TUTORIAL_TIMER_TITLE";
      
      public static const LOC_TUTORIAL_TIP_BLAZING_STEED:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BLAZING_STEED";
      
      public static const LOC_TUTORIAL_TIP_BOOST_BONUS_TIME:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BOOST_BONUS_TIME";
      
      public static const LOC_TUTORIAL_TIP_BOOST_DETONATOR:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BOOST_DETONATOR";
      
      public static const LOC_TUTORIAL_TIP_BOOST_MULTIPLIER:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BOOST_MULTIPLIER";
      
      public static const LOC_TUTORIAL_TIP_BOOST_MYSTERY:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BOOST_MYSTERY";
      
      public static const LOC_TUTORIAL_TIP_BOOST_SCRAMBLER:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_BOOST_SCRAMBLER";
      
      public static const LOC_TUTORIAL_TIP_CATSEYE:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_CATSEYE";
      
      public static const LOC_TUTORIAL_TIP_COIN:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_COIN";
      
      public static const LOC_TUTORIAL_TIP_FIREWORKS:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_FIREWORKS";
      
      public static const LOC_TUTORIAL_TIP_FLAME_GEM:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_FLAME_GEM";
      
      public static const LOC_TUTORIAL_TIP_HYPERCUBE:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_HYPERCUBE";
      
      public static const LOC_TUTORIAL_TIP_KANGARUBY:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_KANGARUBY";
      
      public static const LOC_TUTORIAL_TIP_MOONSTONE:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_MOONSTONE";
      
      public static const LOC_TUTORIAL_TIP_MULTIPLIER:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_MULTIPLIER";
      
      public static const LOC_TUTORIAL_TIP_PHOENIX_PRISM:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_PHOENIX_PRISM";
      
      public static const LOC_TUTORIAL_TIP_STAR_GEM:String = "LOC_BLITZ3GAME_TUTORIAL_TIP_STAR_GEM";
      
      public static const LOC_TUTORIAL_WELCOME:String = "LOC_BLITZ3GAME_TUTORIAL_WELCOME";
      
      public static const LOC_UI_BUTTON_OFFER_RADIO:String = "LOC_BLITZ3GAME_UI_BUTTON_OFFER_RADIO";
      
      public static const LOC_UI_GAMEBOARD_BLAZING_SPEED:String = "LOC_BLITZ3GAME_UI_GAMEBOARD_BLAZING_SPEED";
      
      public static const LOC_UI_GAMEBOARD_BLAZING_STEED:String = "LOC_BLITZ3GAME_UI_GAMEBOARD_BLAZING_STEED";
      
      public static const LOC_UI_GAMEBOARD_LAST_HURRAH:String = "LOC_BLITZ3GAME_UI_GAMEBOARD_LAST_HURRAH";
      
      public static const LOC_UI_GAMESTATS_0SEC:String = "LOC_BLITZ3GAME_UI_GAMESTATS_0SEC";
      
      public static const LOC_UI_GAMESTATS_1MIN:String = "LOC_BLITZ3GAME_UI_GAMESTATS_1MIN";
      
      public static const LOC_UI_GAMESTATS_30SEC:String = "LOC_BLITZ3GAME_UI_GAMESTATS_30SEC";
      
      public static const LOC_UI_GAMESTATS_BTN_CONTINUE:String = "LOC_BLITZ3GAME_UI_GAMESTATS_BTN_CONTINUE";
      
      public static const LOC_UI_GAMESTATS_BTN_PLAY_AGAIN:String = "LOC_BLITZ3GAME_UI_GAMESTATS_BTN_PLAY_AGAIN";
      
      public static const LOC_UI_GAMESTATS_EARNED:String = "LOC_BLITZ3GAME_UI_GAMESTATS_EARNED";
      
      public static const LOC_UI_GAMESTATS_FIRE_GEM:String = "LOC_BLITZ3GAME_UI_GAMESTATS_FIRE_GEM";
      
      public static const LOC_UI_GAMESTATS_HYPERCUBE:String = "LOC_BLITZ3GAME_UI_GAMESTATS_HYPERCUBE";
      
      public static const LOC_UI_GAMESTATS_LAST_HURRAH:String = "LOC_BLITZ3GAME_UI_GAMESTATS_LAST_HURRAH";
      
      public static const LOC_UI_GAMESTATS_LAST_HURRAH_POPUP:String = "LOC_BLITZ3GAME_UI_GAMESTATS_LAST_HURRAH_POPUP";
      
      public static const LOC_UI_GAMESTATS_LH:String = "LOC_BLITZ3GAME_UI_GAMESTATS_LH";
      
      public static const LOC_UI_GAMESTATS_LIGHTNING_GEM:String = "LOC_BLITZ3GAME_UI_GAMESTATS_LIGHTNING_GEM";
      
      public static const LOC_UI_GAMESTATS_MATCHES_DESC:String = "LOC_BLITZ3GAME_UI_GAMESTATS_MATCHES_DESC";
      
      public static const LOC_UI_GAMESTATS_MATCHES_LABEL:String = "LOC_BLITZ3GAME_UI_GAMESTATS_MATCHES_LABEL";
      
      public static const LOC_UI_GAMESTATS_MULTIPLIED:String = "LOC_BLITZ3GAME_UI_GAMESTATS_MULTIPLIED";
      
      public static const LOC_UI_GAMESTATS_NHS:String = "LOC_BLITZ3GAME_UI_GAMESTATS_NHS";
      
      public static const LOC_UI_GAMESTATS_PLUS_5:String = "LOC_BLITZ3GAME_UI_GAMESTATS_PLUS_5";
      
      public static const LOC_UI_GAMESTATS_POINTS:String = "LOC_BLITZ3GAME_UI_GAMESTATS_POINTS";
      
      public static const LOC_UI_GAMESTATS_PTS:String = "LOC_BLITZ3GAME_UI_GAMESTATS_PTS";
      
      public static const LOC_UI_GAMESTATS_SPEED:String = "LOC_BLITZ3GAME_UI_GAMESTATS_SPEED";
      
      public static const LOC_UI_GAMESTATS_SPEED_DESC:String = "LOC_BLITZ3GAME_UI_GAMESTATS_SPEED_DESC";
      
      public static const LOC_UI_GAMESTATS_SPEED_LABEL:String = "LOC_BLITZ3GAME_UI_GAMESTATS_SPEED_LABEL";
      
      public static const LOC_UI_NETWORK_WAIT:String = "LOC_BLITZ3GAME_UI_NETWORK_WAIT";
      
      public static const LOC_UI_NEW_MEDAL:String = "LOC_BLITZ3GAME_UI_NEW_MEDAL";
      
      public static const LOC_UI_NEXT_MEDAL:String = "LOC_BLITZ3GAME_UI_NEXT_MEDAL";
      
      public static const LOC_UI_SUBMIT_SCORE:String = "LOC_BLITZ3GAME_UI_SUBMIT_SCORE";
      
      public static const LOC_UI_THOUSANDS:String = "LOC_BLITZ3GAME_UI_THOUSANDS";
      
      public static const LOC_UI_TOP_MEDAL:String = "LOC_BLITZ3GAME_UI_TOP_MEDAL";
      
      public static const LOC_UPSELL_TEXT_0:String = "LOC_BLITZ3GAME_UPSELL_TEXT_0";
      
      public static const LOC_UPSELL_TEXT_1:String = "LOC_BLITZ3GAME_UPSELL_TEXT_1";
      
      public static const LOC_UPSELL_URL_0:String = "LOC_BLITZ3GAME_UPSELL_URL_0";
      
      public static const LOC_UPSELL_URL_1:String = "LOC_BLITZ3GAME_UPSELL_URL_1";
       
      
      public function Blitz3GameLoc()
      {
         super();
      }
   }
}
